### ISSUE TITLE
Parsers can import from Dump TSVs

### ISSUE THREAD

**Issue by mrdavidgagnon** [fielddaylab/opengamedata-backend#7]

**Comment by LswaN58** [comment]
I think the following Trello card was a duplicate:
"Split code so we have one project that exports the RAW and the feature extractor works on that format (not SQL)"

**Comment by LswaN58** [comment]
Renaming from "Parsers can import from RAW CSVs" to "Dump TSVs." I'm assuming it was supposed to be "TSVs" all along.
